### ISSUE TITLE
اضافه کردن کامنت برای ترجمه و خوانایی بهتر

### ISSUE THREAD

**Issue by mahdiHashemi14** [javascript-tutorial/fa.javascript.info#108]
سلام وقت بخیر
می خواستم بدونم میتونم در صورت نیاز برای ترجمه و خوانایی بهتر در قسمت هایی که کد داریم کامنت اضافه کنم؟
مثلا در این مورد:
![2021-04-11_164643](https://user-images.githubusercontent.com/72219881/114304020-41add900-9ae6-11eb-8047-fc3c8d02e3c7.png)
اینجا همون طوری که داخل README گفته شده من فقط ترجمه کردم:
![2021-04-11_164829](https://user-images.githubusercontent.com/72219881/114304062-73bf3b00-9ae6-11eb-8498-13f0c21f5f0b.png)
و اگه بتونم کامنت اضافه کنم تا خوانایی بهتر بشه اینطوری میشه:
![2021-04-11_164950](https://user-images.githubusercontent.com/72219881/114304079-88033800-9ae6-11eb-8984-b0684638ed65.png)
میتونم همچین کاری کنم؟ 
این مشکل زیاد پیش میاد برای من و با توجه به اینکه متن فارسی از راست به چپ خونده میشه ولی کد از چپ به راست، اگه بتونیم خطوطی که کامنت ندارن رو خودمون برای خوانایی بهتر بهشون کامنت اضافه کنیم بنظرم کمک میکنه.
داخل متن فارسی چون بعدا از RTL استفاده میشه مشکلی پیش نمیاد ولی برای قسمتی که کد وجود داره جمله بهم میریزه.

**Comment by mahdyar** [comment]
Hello @mahdiHashemi14 and thank you for your suggestion,
But since the repo will be syncing with upstream now and then, it can't happen because It'll cause merge conflicts.
