### ISSUE TITLE
RTL Issue in CSS

### ISSUE THREAD

**Issue by kooshan75** [javascript-tutorial/fa.javascript.info#14]
As I was translating files into Persian, I faced an issue relating to the RTL problem. I think somehow we should modify CSS files to support this.
<img width="832" alt="Screen Shot 2019-06-30 at 3 44 27 PM" src="https://user-images.githubusercontent.com/31003395/60395790-0ed36480-9b4e-11e9-971d-3a5dd09b4724.png">

**Comment by mehradsadeghi** [comment]
Hi @kooshan75 . Thanks for your contribution. 
Continue translating the content for now. When we were at the point to publish translated contents to javascript.info, we'll get to edit CSS direction.
