### ISSUE TITLE
راهنمای ترجمه

### ISSUE THREAD

**Issue by mahdiHashemi14** [javascript-tutorial/fa.javascript.info#160]
<div dir="rtl">
سلام وقت بخیر.

بنظر من اگه یه راهنمای ترجمه وجود داشته باشه به فرایند ترجمه کمک میکنه.

مثلا کلمه "syntax" به فارسی «سینتکس» نوشته بشه بهتره. یا مثلا کامنت‌های داخل کد چجوری نوشته بشن که موقع پیاده‌سازی خوانا باشن. یا نکته‌های ترجمه مثلا تیترها با کلمه فارسی شروع بشن.

این راهنما به مترجم‌های جدید هم خیلی میتونه کمک کنه.

اگه موافق باشین باهم این راهنما رو بسازیم. من خودم حین ترجمه هر کلمه‌ای که بنظرم به راهنمایی احتیاج داشته باشه رو بعد از نظرخواهی اضافه میکنم.
</div>

**Comment by mahdyar** [comment]
سلام؛
موافقم! مخصوصاً برای ریویوی پول‌ریکوئست‌ها نیاز نیست هربار این نکات رو کامنت کنم.
نظری ندارید کجا قرار بدیم این نکات رو؟ توی readme اضافه کنیم؟

**Comment by mahdyar** [comment]
We can create a contribution guide:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by iliakan** [comment]
@mahdyar Maybe use `README.md` instead?

There's already such section there: https://github.com/javascript-tutorial/fa.javascript.info#translation-tips

**Comment by mahdyar** [comment]
> @mahdyar Maybe use `README.md` instead?
> 
> There's already such section there: https://github.com/javascript-tutorial/fa.javascript.info#translation-tips

LGTM :)
